### ISSUE TITLE
installation de Daxe

### ISSUE THREAD

**Issue by estrellagrubio** [adopt/daxe#1]
J'ai initié ces questions au forum de Jaxe : "Toujours actif ?" (https://sourceforge.net/p/jaxe/discussion/184273/thread/3f9dfe71/)

 J'essayé de récupérer les paramètres du request (post) en invoquant l'url suivant:
 http://svfisistemas/dle/daxe/daxe_js.html?config=config/XHTML_config.xml&save=http://localhost:9085/EDD/AddFileDB&path=c:\tmp\nuevo.xml

Mais dans le servlet AddFileDB les paramètres "file" et "path" sont nul et aucune donnée ne me garde dans le disque dur. Qu'est-ce que je fais probablement pour récupérer le XML et pour pouvoir le sauver dans une base de données ?

Je joins le servlet AddFileDB

**Comment by damien-git** [comment]
Le paramètre de l'URL donnant le chemin vers le document XML est `file` au lieu de `path`. Par ailleurs, cela doit être un chemin d'URL au lieu d'un chemin système, et si le fichier existe l'éditeur doit pouvoir lire le fichier en faisant une requête GET à ce chemin.

Essayez
http://svfisistemas/dle/daxe/daxe_js.html?config=config/XHTML_config.xml&save=http://localhost:9085/EDD/AddFileDB&file=/mydocuments/nuevo.xml

**Comment by estrellagrubio** [comment]
Merci beaucoup à nouveau!.  J'ai tenté avec l'url suivant:

http://svfisistemas/dle/daxe/daxe_js.html?config=config/XHTML_config.xml&save=http://localhost:9085/EDD/AddFileDB&file=http://svfiapp1/edd/nuevo.html
J'ai pu lire le fichier correctement, mais je ne réussis pas à écrire, bien qu'il ait donné toutes les permissions à "TOUS" les utilisateurs (
![accesolectura](https://cloud.githubusercontent.com/assets/25998070/23353720/37f555e2-fcce-11e6-888e-a39b3d17e3b0.png)
lecture et écriture). 

Qu'est-ce qui peut me manquer? Le fichier a-t-il à être chez le même serveur où le servlet est installé ?

**Comment by damien-git** [comment]
Je n'ai pas essayé, mais je pense que le fichier peut être sur un serveur différent de l'adresse utilisée pour enregistrer, du moment que l'application web est autorisée à faire une requête sur cette adresse.

Je ne comprend pas ce qui ne marche pas: est-ce que la servlet reçoit bien la requête POST, avec tous les champs ? Si oui, l'enregistrement du fichier n'est pas liée à Daxe, c'est au serveur de trouver le moyen d'enregistrer le fichier, qu'il soit sur un autre serveur ou pas (même si c'est évidemment plus simple si le fichier est sur le même serveur).

**Comment by estrellagrubio** [comment]
Le problème est que la servlet reçoit la requête POST, mais les paramètres 'file' et 'path' sont null:

protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
    String file = request.getParameter("file"); // file == NULL
    String path = request.getParameter("path"); pas récu // path == NULL

    boolean error = false;
    // TODO Auto-generated method stub
    if (!error)
        response.getWriter().append("ok");
    else
        response.getWriter().append("error");
}

/**
 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
 */
protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
    // TODO Auto-generated method stub
    doGet(request, response);
}

**Comment by estrellagrubio** [comment]
J'ai réussi à garder les données dans un fichier. Le problème était dans que je ne considérais pas le suivant:
Content-Type:multipart/form-data; boundary=AaB03x

J'avais à récupérer les données à travers d'un autre système, avec
HttpServletRequest#getParts()  (http://stackoverflow.com/questions/3337056/convenient-way-to-parse-incoming-multipart-form-data-parameters-in-a-servlet)

Merci beaucoup!!!!

**Comment by damien-git** [comment]
OK, ça me rassure. Dommage que HttpServletRequest.getParameter() ne gère pas le multipart automatiquement. Il faudrait améliorer la doc de Daxe pour clarifier tout ça.
