### ISSUE TITLE
Parameters into script used to save a document 

### ISSUE THREAD

**Issue by estrellagrubio** [adopt/daxe#2]
Good morning:
I am trying to pass parameters like 'user' in the path of the script I used to save a document (save), but without success. The url that I use is: 

http://svfisistemas/dle/daxe/daxe_js.html?config=config/DESTUD_config.xml&save=http://localhost:9085/EDD/upload?user=ESTRELLA&file=http://svfisistemas/dle/daxe/upload/rojoja.xml

How must I write this parameter "user" to get it from the servlet?
Thank you very much!!!

**Comment by damien-git** [comment]
I am not sure you can pass additional parameters like that (you would have to encode the save URL, and be aware that Daxe is sending a POST request with that URL), but maybe you could set cookies instead ?

**Comment by estrellagrubio** [comment]
Then I will try another approach. Thank you very much.
